<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/_dropna_NaN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv",index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df.isnull() #.isnull() - har bir katakcha tekshiradi

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,False,False,False,False,False,False,True,False,False
1,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...
81,False,False,False,False,False,False,False,False,False
82,False,False,True,False,True,False,False,False,False
86,False,False,False,True,False,False,False,True,False
87,False,False,False,False,True,False,False,False,False
88,False,False,False,False,False,False,True,False,False

In [ ]:
df.isnull().sum()

company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

In [ ]:
len(df)

61

In [ ]:
df.isnull().sum()/len(df)*100

company              0.000000
body-style           0.000000
wheel-base          24.590164
length              21.311475
engine-type         19.672131
num-of-cylinders     0.000000
horsepower          26.229508
average-mileage     24.590164
price                4.918033
dtype: float64

In [ ]:
df.dropna()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0

In [ ]:
len(df.dropna())

14

In [ ]:
df.dropna(columns)

NameError: name 'columns' is not defined

In [ ]:
df.dropna(axis=1)

           company   body-style num-of-cylinders
index
0      alfa-romero  convertible             four
1      alfa-romero  convertible             four
2      alfa-romero    hatchback              six
3             audi        sedan             four
4             audi        sedan             five
...            ...          ...              ...
81      volkswagen        sedan             four
82      volkswagen        sedan             four
86      volkswagen        sedan             four
87           volvo        sedan             four
88           volvo        wagon             four

[61 rows x 3 columns]

In [ ]:
df.dropna(axis=1,thresh=48)

           company   body-style  length engine-type num-of-cylinders    price
index
0      alfa-romero  convertible   168.8        dohc             four  13495.0
1      alfa-romero  convertible   168.8        dohc             four  16500.0
2      alfa-romero    hatchback   171.2        ohcv              six  16500.0
3             audi        sedan   176.6         ohc             four  13950.0
4             audi        sedan   176.6         ohc             five  17450.0
...            ...          ...     ...         ...              ...      ...
81      volkswagen        sedan   171.7         ohc             four   7975.0
82      volkswagen        sedan   171.7         NaN             four   7995.0
86      volkswagen        sedan     NaN         ohc             four   9995.0
87           volvo        sedan   188.8         NaN             four  12940.0
88           volvo        wagon   188.8         ohc             four  13415.0

[61 rows x 6 columns]

In [ ]:
df.dropna(subset='price')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
9,bmw,sedan,101.2,NaN,ohc,four,NaN,23.0,16430.0
10,bmw,sedan,NaN,176.8,ohc,four,101.0,23.0,16925.0
11,bmw,sedan,101.2,176.8,ohc,six,121.0,NaN,20970.0
13,bmw,sedan,103.5,189.0,ohc,six,NaN,16.0,30760.0
14,bmw,sedan,103.5,NaN,ohc,six,182.0,16.0,41315.0
15,bmw,sedan,110.0,197.0,ohc,six,182.0,NaN,36880.0
16,chevrolet,hatchback,88.4,141.1,l,three,NaN,47.0,5151.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
18,chevrolet,sedan,NaN,158.8,ohc,four,70.0,NaN,6575.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
20,dodge,hatchback,93.7,NaN,ohc,four,68.0,NaN,6229.0
27,honda,wagon,96.5,NaN,ohc,four,76.0,30.0,7295.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
29,honda,sedan,NaN,169.1,ohc,four,NaN,25.0,10345.0
30,isuzu,sedan,NaN,170.7,ohc,four,78.0,24.0,6785.0
33,jaguar,sedan,113.0,NaN,dohc,six,NaN,15.0,32250.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
35,jaguar,sedan,NaN,191.7,ohcv,twelve,262.0,13.0,36000.0
36,mazda,hatchback,93.1,159.1,NaN,four,NaN,NaN,5195.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
39,mazda,hatchback,NaN,NaN,NaN,two,101.0,17.0,11845.0
43,mazda,sedan,104.9,175.0,ohc,four,NaN,NaN,18344.0
44,mercedes-benz,sedan,110.0,190.9,NaN,five,123.0,22.0,25552.0
45,mercedes-benz,wagon,NaN,190.9,ohc,five,123.0,22.0,28248.0
46,mercedes-benz,sedan,120.9,208.1,NaN,eight,184.0,14.0,40960.0
47,mercedes-benz,hardtop,112.0,199.2,NaN,eight,184.0,14.0,45400.0
49,mitsubishi,hatchback,NaN,157.3,ohc,four,NaN,37.0,5389.0
50,mitsubishi,hatchback,93.7,NaN,NaN,four,68.0,31.0,6189.0
51,mitsubishi,sedan,96.3,172.4,NaN,four,88.0,NaN,6989.0
52,mitsubishi,sedan,96.3,172.4,ohc,four,NaN,25.0,8189.0
53,nissan,sedan,NaN,NaN,ohc,four,55.0,NaN,7099.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
55,nissan,sedan,NaN,165.3,ohc,four,69.0,31.0,6849.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
57,nissan,sedan,100.4,184.6,ohcv,six,152.0,NaN,13499.0
61,porsche,hardtop,NaN,NaN,NaN,six,207.0,17.0,34028.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,NaN,four,NaN,31.0,6338.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,NaN,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0
80,volkswagen,sedan,97.3,NaN,ohc,four,NaN,37.0,7775.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [9]:
df.dropna(subset=['price','wheel-base'])

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
9,bmw,sedan,101.2,NaN,ohc,four,NaN,23.0,16430.0
11,bmw,sedan,101.2,176.8,ohc,six,121.0,NaN,20970.0
13,bmw,sedan,103.5,189.0,ohc,six,NaN,16.0,30760.0
14,bmw,sedan,103.5,NaN,ohc,six,182.0,16.0,41315.0
15,bmw,sedan,110.0,197.0,ohc,six,182.0,NaN,36880.0
16,chevrolet,hatchback,88.4,141.1,l,three,NaN,47.0,5151.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
20,dodge,hatchback,93.7,NaN,ohc,four,68.0,NaN,6229.0
27,honda,wagon,96.5,NaN,ohc,four,76.0,30.0,7295.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
33,jaguar,sedan,113.0,NaN,dohc,six,NaN,15.0,32250.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
36,mazda,hatchback,93.1,159.1,NaN,four,NaN,NaN,5195.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
43,mazda,sedan,104.9,175.0,ohc,four,NaN,NaN,18344.0
44,mercedes-benz,sedan,110.0,190.9,NaN,five,123.0,22.0,25552.0
46,mercedes-benz,sedan,120.9,208.1,NaN,eight,184.0,14.0,40960.0
47,mercedes-benz,hardtop,112.0,199.2,NaN,eight,184.0,14.0,45400.0
50,mitsubishi,hatchback,93.7,NaN,NaN,four,68.0,31.0,6189.0
51,mitsubishi,sedan,96.3,172.4,NaN,four,88.0,NaN,6989.0
52,mitsubishi,sedan,96.3,172.4,ohc,four,NaN,25.0,8189.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
57,nissan,sedan,100.4,184.6,ohcv,six,152.0,NaN,13499.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
67,toyota,hatchback,95.7,158.7,NaN,four,NaN,31.0,6338.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,NaN,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0
80,volkswagen,sedan,97.3,NaN,ohc,four,NaN,37.0,7775.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0