<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/_map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv",index_col=0)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
df.shape

(61, 9)

In [ ]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [ ]:
dict={'two':2,'three':3,'four':4,'five':5,'six':6,'eight':8,'twelve':12}
df['cylinders']=df['num-of-cylinders'].map(dict)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,NaN
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,NaN
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,NaN
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,NaN
4,audi,sedan,99.4,176.6,ohc,5,NaN,NaN,17450.0,NaN

In [ ]:
df['price']

index
0     13495.0
1     16500.0
2     16500.0
3     13950.0
4     17450.0
       ...
81     7975.0
82     7995.0
86     9995.0
87    12940.0
88    13415.0
Name: price, Length: 61, dtype: float64

In [ ]:
kurs=10720
df['price_uz']=df['price'].map(lambda x: x*kurs)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,NaN,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,NaN,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,NaN,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,NaN,149544000.0
4,audi,sedan,99.4,176.6,ohc,5,NaN,NaN,17450.0,NaN,187064000.0

In [ ]:
fuel_dict = {'gas': 1, 'diesel': 2}
df['fuel-num']=df['fuel-type'].map(fuel_dict)
df

KeyError: 'fuel-type'

In [ ]:
dict = {'two':2, 'four':4}
df['doors_num'] = df['num-of-doors'].map(dict)