<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/Amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/uzbekistan.csv', index_col=0)
df.columns = ['maydoni','aholisi']
df

                                maydoni    aholisi
Boʻlinishi
Andijon viloyati                 4200.0  1899000.0
Buxoro viloyati                 39400.0  1384700.0
Fargʻona viloyati                6800.0  2597000.0
Jizzax viloyati                 20500.0   910500.0
Xorazm viloyati                  6300.0  1200000.0
Namangan viloyati                7900.0  1862000.0
Navoiy viloyati                110800.0   767500.0
Qashqadaryo viloyati            28400.0  2029000.0
Qoraqalpogʻiston Respublikasi  160000.0  1200000.0
Samarqand viloyati              16400.0  2322000.0
Sirdaryo viloyati                5100.0   648100.0
Surxondaryo viloyati            20800.0  1676000.0
Toshkent viloyati               15300.0  4450000.0

In [ ]:
df.sum()

maydoni      441900.0
aholisi    22945800.0
dtype: float64

In [ ]:
df.sum(axis='columns')

Boʻlinishi
Andijon viloyati                 1903200.0
Buxoro viloyati                  1424100.0
Fargʻona viloyati                2603800.0
Jizzax viloyati                   931000.0
Xorazm viloyati                  1206300.0
Namangan viloyati                1869900.0
Navoiy viloyati                   878300.0
Qashqadaryo viloyati             2057400.0
Qoraqalpogʻiston Respublikasi    1360000.0
Samarqand viloyati               2338400.0
Sirdaryo viloyati                 653200.0
Surxondaryo viloyati             1696800.0
Toshkent viloyati                4465300.0
dtype: float64

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/gm_sales.csv', index_col=0)
df

         2020   2021
Labo     4521   7542
Damas   30889  33682
Spark   16370   6485
Nexia   41663  14442
Cobalt  44901  36317
Gentra  30368  26266

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/merc.csv')
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0
...,...,...,...,...,...,...,...,...,...
13114,C Class,2020,35999,Automatic,500,Diesel,145,55.4,2.0
13115,B Class,2020,24699,Automatic,2500,Diesel,145,55.4,2.0
13116,GLC Class,2019,30999,Automatic,11612,Diesel,145,41.5,2.1
13117,CLS Class,2019,37990,Automatic,2426,Diesel,145,45.6,2.0
13118,S Class,2019,54999,Automatic,2075,Diesel,145,52.3,2.9

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13119 entries, 0 to 13118
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         13119 non-null  object
 1   year          13119 non-null  int64
 2   price         13119 non-null  int64
 3   transmission  13119 non-null  object
 4   mileage       13119 non-null  int64
 5   fuelType      13119 non-null  object
 6   tax           13119 non-null  int64
 7   mpg           13119 non-null  float64
 8   engineSize    13119 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 922.6+ KB

In [ ]:
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0
...,...,...,...,...,...,...,...,...,...
13114,C Class,2020,35999,Automatic,500,Diesel,145,55.4,2.0
13115,B Class,2020,24699,Automatic,2500,Diesel,145,55.4,2.0
13116,GLC Class,2019,30999,Automatic,11612,Diesel,145,41.5,2.1
13117,CLS Class,2019,37990,Automatic,2426,Diesel,145,45.6,2.0
13118,S Class,2019,54999,Automatic,2075,Diesel,145,52.3,2.9

In [ ]:
df['year'].corr(df['mileage'])

np.float64(-0.7380268515364232)

In [ ]:
df['price'].corr(df['engineSize'])

np.float64(0.5161257786169436)

In [ ]:
df.corr(numeric_only=True) # butun jadvalni solishtiradi

                year     price   mileage       tax       mpg  engineSize
year        1.000000  0.520712 -0.738027  0.012480 -0.094626   -0.142147
price       0.520712  1.000000 -0.537214  0.268717 -0.438445    0.516126
mileage    -0.738027 -0.537214  1.000000 -0.160223  0.202850    0.063652
tax         0.012480  0.268717 -0.160223  1.000000 -0.513742    0.338341
mpg        -0.094626 -0.438445  0.202850 -0.513742  1.000000   -0.339862
engineSize -0.142147  0.516126  0.063652  0.338341 -0.339862    1.000000

In [ ]:
df.corrwith(df['price'], numeric_only=True) # bitta ustun bilan solishtiradi

year          0.520712
price         1.000000
mileage      -0.537214
tax           0.268717
mpg          -0.438445
engineSize    0.516126
dtype: float64

In [ ]:
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0
...,...,...,...,...,...,...,...,...,...
13114,C Class,2020,35999,Automatic,500,Diesel,145,55.4,2.0
13115,B Class,2020,24699,Automatic,2500,Diesel,145,55.4,2.0
13116,GLC Class,2019,30999,Automatic,11612,Diesel,145,41.5,2.1
13117,CLS Class,2019,37990,Automatic,2426,Diesel,145,45.6,2.0
13118,S Class,2019,54999,Automatic,2075,Diesel,145,52.3,2.9

In [ ]:
models = df['model'].unique()
models.sort()
models

array([' A Class', ' B Class', ' C Class', ' CL Class', ' CLA Class',
       ' CLC Class', ' CLK', ' CLS Class', ' E Class', ' G Class',
       ' GL Class', ' GLA Class', ' GLB Class', ' GLC Class',
       ' GLE Class', ' GLS Class', ' M Class', ' R Class', ' S Class',
       ' SL CLASS', ' SLK', ' V Class', ' X-CLASS', '180', '200', '220',
       '230'], dtype=object)

In [ ]:
models = df['year'].unique()
models.sort()
models

array([1970, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       2018, 2019, 2020])