<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/Amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'ism': ['Ali', 'Vali', 'Guli', 'Sami', 'Doni'],
    'shahar': ['Toshkent', 'Andijon', 'Farg\'ona', 'Toshkent', 'Namangan']
})

In [ ]:
df

    ism    shahar
0   Ali  Toshkent
1  Vali   Andijon
2  Guli  Farg'ona
3  Sami  Toshkent
4  Doni  Namangan

In [ ]:
df2=df['shahar'].isin(['Toshkent', 'Andijon'])
df2

0     True
1     True
2    False
3     True
4    False
Name: shahar, dtype: bool

In [ ]:
df[df2]

    ism    shahar
0   Ali  Toshkent
1  Vali   Andijon
3  Sami  Toshkent

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'ism': ['Ali', 'Vali', 'Guli', np.nan],
    'yosh': [25, np.nan, 30, 40]

})

In [ ]:
df

    ism  yosh
0   Ali  25.0
1  Vali   NaN
2  Guli  30.0
3   NaN  40.0

In [ ]:
df.dropna()

    ism  yosh
0   Ali  25.0
2  Guli  30.0

In [ ]:
df.dropna(how='all')

    ism  yosh
0   Ali  25.0
1  Vali   NaN
2  Guli  30.0
3   NaN  40.0

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'ism': ['Ali', 'Vali', 'Guli', 'Doni'],
    'yosh': [25, np.nan, 30, np.nan]
})
df

    ism  yosh
0   Ali  25.0
1  Vali   NaN
2  Guli  30.0
3  Doni   NaN

In [ ]:
df['yosh'].fillna(0,inplace=True)
df

/tmp/ipykernel_1659/1369830092.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['yosh'].fillna(0,inplace=True)

    ism  yosh
0   Ali  25.0
1  Vali   0.0
2  Guli  30.0
3  Doni   0.0

In [ ]:
df['yosh']=df['yosh'].fillna(0)
df

    ism  yosh
0   Ali  25.0
1  Vali   0.0
2  Guli  30.0
3  Doni   0.0

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'ism': ['Ali', 'Vali', 'Ali', 'Guli', 'Vali'],
    'yosh': [25, 30, 25, 22, 30]
})
df

    ism  yosh
0   Ali    25
1  Vali    30
2   Ali    25
3  Guli    22
4  Vali    30

In [ ]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'ism': ['Ali', 'Vali', 'Ali', 'Guli', 'Vali'],
    'yosh': [25, 30, 25, 22, 30]
})
df

    ism  yosh
0   Ali    25
1  Vali    30
2   Ali    25
3  Guli    22
4  Vali    30

In [ ]:
df.drop_duplicates()

    ism  yosh
0   Ali    25
1  Vali    30
3  Guli    22

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'shahar': ['Toshkent', 'Andijon', 'Toshkent', 'Namangan', 'Toshkent', 'Andijon']
})
df

     shahar
0  Toshkent
1   Andijon
2  Toshkent
3  Namangan
4  Toshkent
5   Andijon

In [ ]:
df['shahar'].value_counts()

shahar
Toshkent    3
Andijon     2
Namangan    1
Name: count, dtype: int64

In [ ]:
df['shahar'].unique()

array(['Toshkent', 'Andijon', 'Namangan'], dtype=object)

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'shahar': ['Toshkent', 'Andijon', 'Toshkent', 'Namangan']
})
df

     shahar
0  Toshkent
1   Andijon
2  Toshkent
3  Namangan

In [ ]:
df['shahar'].replace('Toshkent','TSH')

0         TSH
1     Andijon
2         TSH
3    Namangan
Name: shahar, dtype: object

In [ ]:
df['shahar'].replace({'Toshkent':'TSH','Andijon':'AND'})

0         TSH
1         AND
2         TSH
3    Namangan
Name: shahar, dtype: object

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'shahar': ['Toshkent', 'Andijon', 'Namangan']
})
df

     shahar
0  Toshkent
1   Andijon
2  Namangan

In [ ]:
df['shahar'].map(lambda x: len(x))

0    8
1    7
2    8
Name: shahar, dtype: int64

In [ ]:
df['shahar'].map(len)

0    8
1    7
2    8
Name: shahar, dtype: int64

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'ism': ['Ali', 'Vali', 'Guli'],
    'yosh': [25, 30, 22]
})
df

    ism  yosh
0   Ali    25
1  Vali    30
2  Guli    22

In [ ]:
df['yosh'].apply(lambda x: x+1)

0    26
1    31
2    23
Name: yosh, dtype: int64

In [ ]:
df.rename(columns={'yosh':'age'})

    ism  age
0   Ali   25
1  Vali   30
2  Guli   22