<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/cut_qcut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import numpy as np

In [30]:
df=pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population.csv', usecols=['country','pop2021','area'], index_col='country')
df.head()

            pop2021  area
country
Macau       658.394    30
Monaco       39.511     2
Singapore  5896.686   710
Hong Kong  7552.810  1104
Gibraltar    33.698     6

In [37]:
df.loc['Uzbekistan']

pop2021         33935.763
area               447400
guruhc     (30000, 50000]
Name: Uzbekistan, dtype: object

In [ ]:
bins=[0,1000,10000,30000,50000,100000,300000,1500000]
population = df.pop2021

In [36]:
population

country
Macau                658.394
Monaco                39.511
Singapore           5896.686
Hong Kong           7552.810
Gibraltar             33.698
                      ...
Namibia             2587.344
Western Sahara       611.875
Mongolia            3329.289
Falkland Islands       3.533
Greenland             56.877
Name: pop2021, Length: 232, dtype: float64

In [35]:
guruh = pd.cut(population,bins)
guruh

country
Macau               (0, 10000]
Monaco              (0, 10000]
Singapore           (0, 10000]
Hong Kong           (0, 10000]
Gibraltar           (0, 10000]
                       ...
Namibia             (0, 10000]
Western Sahara      (0, 10000]
Mongolia            (0, 10000]
Falkland Islands    (0, 10000]
Greenland           (0, 10000]
Name: pop2021, Length: 232, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 50000]]

In [34]:
guruh.value_counts()

pop2021
(0, 1000]            72
(1000, 10000]        68
(10000, 30000]       44
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: count, dtype: int64

In [33]:
df['guruhc']= guruh
df.head()

            pop2021  area         guruhc
country
Macau       658.394    30      (0, 1000]
Monaco       39.511     2      (0, 1000]
Singapore  5896.686   710  (1000, 10000]
Hong Kong  7552.810  1104  (1000, 10000]
Gibraltar    33.698     6      (0, 1000]

In [43]:
df.pop2021.value_counts()

pop2021
658.394     1
39.511      1
5896.686    1
7552.810    1
33.698      1
           ..
2587.344    1
611.875     1
3329.289    1
3.533       1
56.877      1
Name: count, Length: 232, dtype: int64

In [ ]:
df=pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv",index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df.price.describe()

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [ ]:
bins = [0,10000,20000,50000]
range =pd.cut(df.price,bins)
range

index
0     (10000, 20000]
1     (10000, 20000]
2     (10000, 20000]
3     (10000, 20000]
4     (10000, 20000]
           ...
81        (0, 10000]
82        (0, 10000]
86        (0, 10000]
87    (10000, 20000]
88    (10000, 20000]
Name: price, Length: 61, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 50000]]

In [ ]:
range.value_counts()

price
(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: count, dtype: int64

In [ ]:
names= ['arzon',"o'rta",'qimmat']
range=pd.cut(df.price,bins,labels=names)

range.value_counts()

price
arzon     28
o'rta     17
qimmat    13
Name: count, dtype: int64

In [ ]:
range = pd.cut(df.price,5)
range.value_counts()

price
(5110.751, 13200.8]    32
(13200.8, 21250.6]     14
(29300.4, 37350.2]      7
(37350.2, 45400.0]      3
(21250.6, 29300.4]      2
Name: count, dtype: int64

In [ ]:
range=pd.qcut(df.horsepower,3)
range.value_counts()

horsepower
(51.999, 70.0]    18
(112.0, 262.0]    15
(70.0, 112.0]     12
Name: count, dtype: int64

In [ ]:
df['mileage_guruh'] =pd.cut('average-mileage',[0,20,30,40,60])