<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
data = {
    'apples': [3, 2, 0, 1],
    'oranges': [0, 3, 7, 2]
}
df = pd.DataFrame(data)
#print(df)    #  ro'yxat to'liq chiqadi
df.head()    #  ro'yxat 2 qator chiqadi
data

{'apples': [3, 2, 0, 1], 'oranges': [0, 3, 7, 2]}

In [ ]:
df = pd.DataFrame(data,columns=['apples','oranges','narx','sotildi'])
df  # columns - DataFrame parametr, ustunlarga nom berish uchun.

   apples  oranges narx sotildi
0       3        0  NaN     NaN
1       2        3  NaN     NaN
2       0        7  NaN     NaN
3       1        2  NaN     NaN

In [ ]:
df = pd.DataFrame(data,columns=['apples','oranges','narx','sotildi'],index=['a','b','c','d'])
df
df

   apples  oranges narx sotildi
a       3        0  NaN     NaN
b       2        3  NaN     NaN
c       0        7  NaN     NaN
d       1        2  NaN     NaN

In [ ]:
df.sotildi = 0
df

   apples  oranges narx  sotildi
a       3        0  NaN        0
b       2        3  NaN        0
c       0        7  NaN        0
d       1        2  NaN        0

In [ ]:
df[['sotildi','narx']] = 0 # 2 ta ustinni bir vaqtda 0 qilish
df

   apples  oranges  narx  sotildi
a       3        0     0        0
b       2        3     0        0
c       0        7     0        0
d       1        2     0        0

In [ ]:
df[['sotildi','narx']] = [0,1]  # 2 ta ustinni bir vaqtda har xil qiymat beris
df

   apples  oranges  narx  sotildi
a       3        0     1        0
b       2        3     1        0
c       0        7     1        0
d       1        2     1        0

In [ ]:
data = {
    'Uzbekistan':{2021:33.9,2020:33.5,2019:32.9,2018:32.5,2017:31.9},
    'Kazakhstan':{2021:18.9,2020:18.7,2019:18.5,2018:18.3,2017:18.1,2016:17.8},
}
df2 = pd.DataFrame(data)
df2

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [ ]:
df2.index.name ="Yil"
df2

      Uzbekistan  Kazakhstan
Yil
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [ ]:
df2 = pd.DataFrame(data,index=[2021,2019,2017])
df2

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2019        32.9        18.5
2017        31.9        18.1

In [ ]:
df2.T # ustun va qatorlar almashadi

            2021  2019  2017
Uzbekistan  33.9  32.9  31.9
Kazakhstan  18.9  18.5  18.1