<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/PS_Index_metodlar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [ ]:
usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455","javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com","javohir":"javohir445@gmail.com"}

data  = {
    "username":usernames,
    "email":emails
}

df = pd.DataFrame(data)
df.index

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

In [ ]:
arr = ['anvar', 'olim', 'maryam', 'javohir']
arr[0]

'anvar'

In [ ]:
data2 = {
    'username':{"olim":"olimjon21", "maryam":"maryam2020"},
    'email':{"olim":"olimjon21@mail.ru", "maryam":"maryam20@gmail.com"}
}
df2 = pd.concat([df,pd.DataFrame(data2)])
df2
pd.concat([df,pd.DataFrame(data2)])

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [ ]:
newind = pd.Index(['olim','Nafisa','Hamida']) # index yaratildi
newind

Index(['olim', 'Nafisa', 'Hamida'], dtype='object')

In [ ]:
newind.isin(df2.index) # isin - jadvallarni solishtiradi

array([ True, False, False])

In [ ]:
df2.index.difference(newind) # difference - jadvallar farqi

Index(['anvar', 'javohir', 'maryam'], dtype='object')

In [ ]:
newind.difference(df2.index) # yuqoridagining aksi

Index(['Hamida', 'Nafisa'], dtype='object')

In [ ]:
df2.index.union(newind) # union - jadvallarni birlashtiradi

Index(['Hamida', 'Nafisa', 'anvar', 'javohir', 'maryam', 'maryam', 'olim',
       'olim'],
      dtype='object')

In [ ]:
newind.drop('olim') # drop - o'chirish

Index(['Nafisa', 'Hamida'], dtype='object')

In [ ]:
s = pd.Series([120, 85, 200, 60], index=['non', 'sut', 'guruch', 'yog'])
s.index

Index(['non', 'sut', 'guruch', 'yog'], dtype='object')

In [ ]:
type(s.index)

pandas.core.indexes.base.Index

In [ ]:
s

non       120
sut        85
guruch    200
yog        60
dtype: int64

In [4]:
s = pd.Series([120, 85, 200, 60], index=['non', 'sut', 'guruch', 'yog'])
'sut' in s.index

True

In [5]:
s

non       120
sut        85
guruch    200
yog        60
dtype: int64

In [6]:
s.index.name = 'Mahsulotlar'
s

Mahsulotlar
non       120
sut        85
guruch    200
yog        60
dtype: int64

In [7]:
s.name = "Narx"
s

Mahsulotlar
non       120
sut        85
guruch    200
yog        60
Name: Narx, dtype: int64

In [10]:
s1 = pd.Series([1,2,3], index=['a','b','c'])
s2 = pd.Series([4,5,6], index=['b','c','d'])

s1.index.union(s2.index)
s1

a    1
b    2
c    3
dtype: int64