<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/Series_metodlari.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from pandas import Series
cars_dictionary = {'Malibu':40000, 'Lacetti':20000, 'Toyota':10000, 'Mazda':5000}
models = ['Honda', 'Mazda', 'Lacetti', 'Jaguar', 'Malibu', 'Toyota''Chevrolet','Lada']
cars2 = Series(cars_dictionary, index=models)
cars2

Honda                  NaN
Mazda               5000.0
Lacetti            20000.0
Jaguar                 NaN
Malibu             40000.0
ToyotaChevrolet        NaN
Lada                   NaN
dtype: float64

In [5]:
cars2.isnull() # isnul() - ro'yxatda mavjud False,yo'q bo'lsa True qayataradi

Honda               True
Mazda              False
Lacetti            False
Jaguar              True
Malibu             False
ToyotaChevrolet     True
Lada                True
dtype: bool

In [6]:
cars2.notnull() #usnul() ning teskarisi

Honda              False
Mazda               True
Lacetti             True
Jaguar             False
Malibu              True
ToyotaChevrolet    False
Lada               False
dtype: bool

In [8]:
cars2

Honda                  NaN
Mazda               5000.0
Lacetti            20000.0
Jaguar                 NaN
Malibu             40000.0
ToyotaChevrolet        NaN
Lada                   NaN
dtype: float64

In [10]:
cars_dictionary

{'Malibu': 40000, 'Lacetti': 20000, 'Toyota': 10000, 'Mazda': 5000}

In [11]:
cars_dictionary+cars2

TypeError: unsupported operand type(s) for +: 'dict' and 'float'