<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/takroriy_qiymat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv')
df.head()

   rank  country     density   densityMi    pop2021   area
0     1    Macau  21946.4667  56841.3487    658.394     30
1     2   Monaco  19755.5000  51166.7450     39.511      2
2    28  Burundi    440.3044   1140.3884  12255.433  27834
3     1    Macau  21946.4667  56841.3487    658.394     30
4     2   Monaco  19755.5000  51166.7450     39.511      2

In [8]:
df.duplicated()

0      False
1      False
2      False
3       True
4       True
       ...
242    False
243    False
244    False
245    False
246    False
Length: 247, dtype: bool

In [9]:
df.shape

(247, 6)

In [10]:
df.duplicated().sum() # necha qator takrorlangan

np.int64(15)

In [12]:
df2=df.drop_duplicates()
df2

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

In [13]:
df2.shape

(232, 6)

In [15]:
df.drop_duplicates(['country'])

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]