<a href="https://colab.research.google.com/github/maqsud1987/Data_Science/blob/main/Tartiblash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

df = pd.DataFrame(np.random.randn(3,4),columns=['Olma','Anor','Qovun','Anjir'],index = list('abc'))
df

       Olma      Anor     Qovun     Anjir
a -0.244171 -0.053181 -0.699023  0.402676
b  2.010504 -0.177548 -1.516215  0.893377
c  0.918918  1.974765 -1.052763  0.390983

In [2]:
np.abs(df) # qiymatlarni musbat qaytaradi

       Olma      Anor     Qovun     Anjir
a  0.244171  0.053181  0.699023  0.402676
b  2.010504  0.177548  1.516215  0.893377
c  0.918918  1.974765  1.052763  0.390983

In [3]:
df

       Olma      Anor     Qovun     Anjir
a -0.244171 -0.053181 -0.699023  0.402676
b  2.010504 -0.177548 -1.516215  0.893377
c  0.918918  1.974765 -1.052763  0.390983

In [4]:
df = pd.DataFrame(np.arange(1,13).reshape(3,4),index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

   Olma  Anor  Qovun  Anjir
a     1     2      3      4
b     5     6      7      8
c     9    10     11     12

In [6]:
df.map(lambda x: x*x)

   Olma  Anor  Qovun  Anjir
a     1     4      9     16
b    25    36     49     64
c    81   100    121    144

In [11]:
obj = pd.Series(range(4),index =['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [12]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [14]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [15]:
df.shape

(2499, 12)

In [16]:
df.sort_index(axis=1).head()

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018

In [18]:
df['rating'] = df['year'].rank()
df

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rating
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left,70.5
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,115.0
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left,1362.0
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,336.5
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,1362.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left,2005.5
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left,1362.0
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left,1362.0
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left,1362.0
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left,1362.0